import React from 'react';
import { DesignErrorItem, SafetyItem, VeItem, ReviewItem } from '../types';
import { Printer, FileText, ShieldAlert, Coins, AlertTriangle } from 'lucide-react';

export const ReportView: React.FC<{ reviewItems: ReviewItem[]; designErrors: DesignErrorItem[]; safetyItems: SafetyItem[]; veItems: VeItem[] }> = ({ reviewItems, designErrors, safetyItems, veItems }) => {
  const markups = reviewItems.flatMap((item) => item.markups || []);
  return <div className="mx-auto max-w-6xl space-y-6 pb-12" id="integrated-report">
    <div className="flex items-center justify-between rounded-2xl bg-[#0f2d55] p-6 text-white"><div><h1 className="text-2xl font-bold tracking-tight">FutureM Ai ENG 통합 검토 보고서</h1><p className="mt-2 text-sm text-blue-100">설계 주석 · 안전 검토 · 원가절감(VE) 통합 결과</p></div><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg bg-white px-4 py-2 text-sm font-bold text-[#123b78]"><Printer className="h-4 w-4" /> 보고서 출력</button></div>
    <div className="grid grid-cols-1 gap-4 md:grid-cols-3"><div className="rounded-xl border border-red-200 bg-red-50 p-5"><AlertTriangle className="mb-3 h-6 w-6 text-red-600" /><b className="text-sm text-red-900">설계 검토</b><strong className="mt-2 block text-2xl text-red-700">{designErrors.length + markups.length}건</strong></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-5"><ShieldAlert className="mb-3 h-6 w-6 text-amber-600" /><b className="text-sm text-amber-900">안전 검토</b><strong className="mt-2 block text-2xl text-amber-700">{safetyItems.length}건</strong></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><Coins className="mb-3 h-6 w-6 text-emerald-600" /><b className="text-sm text-emerald-900">원가절감(VE)</b><strong className="mt-2 block text-2xl text-emerald-700">₩{veItems.reduce((sum, item) => sum + item.impactKw, 0).toLocaleString()}</strong></div></div>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-4 flex items-center gap-2 text-lg font-bold text-[#123b78]"><FileText className="h-5 w-5 text-blue-600" /> 설계 및 주석 검토</h2>{designErrors.length || markups.length ? <div className="space-y-3">{[...designErrors.map((item) => ({ title: item.description, detail: item.suggestedFix, severity: item.severity })), ...markups.map((item) => ({ title: item.title, detail: item.comment, severity: item.severity }))].map((item, index) => <div key={index} className="rounded-lg border border-slate-200 p-4"><div className="flex justify-between gap-3"><b className="text-sm text-slate-800">{item.title}</b><span className="text-xs font-bold text-red-600">{item.severity}</span></div><p className="mt-2 text-xs leading-5 text-slate-600">{item.detail || '상세 의견 없음'}</p></div>)}</div> : <p className="text-sm text-slate-500">현재 세션의 설계 주석이 없습니다.</p>}</section>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="mb-4 text-lg font-bold text-[#123b78]">안전 및 원가절감 검토</h2><div className="space-y-3">{safetyItems.map((item) => <div key={item.id} className="rounded-lg border border-amber-200 bg-amber-50 p-4"><b className="text-sm">{item.summary}</b><p className="mt-1 text-xs text-slate-600">{item.details || item.lawRegulation}</p></div>)}{veItems.map((item) => <div key={item.id} className="rounded-lg border border-emerald-200 bg-emerald-50 p-4"><b className="text-sm">{item.description}</b><p className="mt-1 text-xs text-slate-600">절감액 ₩{item.impactKw.toLocaleString()} · {item.calculationBasis || '산출 근거 없음'}</p></div>)}{!safetyItems.length && !veItems.length && <p className="text-sm text-slate-500">현재 세션의 안전·원가절감 결과가 없습니다.</p>}</div></section>
  </div>;
};
